version: '2'
services:
  mongo:
    image: mongo:3.6.17
    # volumes:
    #     - ~/volumes/jhipster/front/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=front
    ports:
      - 27017:27017
